intervalSec: 20
reportIntervalMinutes: 2
logDir: "/home/alex/Work/WorkTracer/worktracer_data"
logFile: "daily_accumulated.log"
enableLogging: true
ignoredProcesses: [telegram, discord, chrome, slack]
yandexFolderId: "" # YOUR_YANDEX_FOLDER_ID_HERE
yandexApiKey: "" # YOUR_YANDEX_API_KEY_HERE